# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# development:
#  adapter: postgresql
#  database: pg_development
#  pool: 30
#  host: <%= ENV['PG_HOST'] %>
#  username: <%= ENV['PG_USERNAME'] %>
#  password: <%= ENV['PG_PASSWORD'] %>

# test:
#  adapter: postgresql
#  database: pg_test
#  host: <%= ENV['PG_HOST'] %>
#  username: <%= ENV['PG_USERNAME'] %>
#  password: <%= ENV['PG_PASSWORD'] %>

# production:
#  adapter: postgresql
#  database: <%= ENV['PG_DATABASE'] %>
#  pool: 30
#  host: <%= ENV['PG_HOST'] %>
#  username: <%= ENV['SMMS_DATABASE_USERNAME'] %>
#  password: <%= ENV['SMMS_DATABASE_PASSWORD'] %>
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: 123123123
  port: 3306

development:
  <<: *default
  host: 127.0.0.1
  password: 123123123
  database: marroi_middle_dev

staging:
  <<: *default
  password: 12yhnji3
  database: marroi_middle_staging

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

production:
  <<: *default
  password: 12yhnji3
  database: marroi_middle_production