# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
 adapter: postgresql
 database: pg_development
 pool: 30
 host: <%= ENV['PG_HOST'] %>
 username: <%= ENV['PG_USERNAME'] %>
 password: <%= ENV['PG_PASSWORD'] %>

test:
 adapter: postgresql
 database: pg_test
 host: <%= ENV['PG_HOST'] %>
 username: <%= ENV['PG_USERNAME'] %>
 password: <%= ENV['PG_PASSWORD'] %>

production:
 adapter: postgresql
 database: <%= ENV['PG_DATABASE'] %>
 pool: 30
 host: <%= ENV['PG_HOST'] %>
 username: <%= ENV['SMMS_DATABASE_USERNAME'] %>
 password: <%= ENV['SMMS_DATABASE_PASSWORD'] %>
